### ISSUE TITLE
Built site has links to "react-exhibit" instead of your project name

### ISSUE THREAD

**Issue by Tanhe** [au-re/generator-react-exhibit#1]
Links to components end up being of the form "/react-exhibit/[component]" and the link back to the project is also to "/react-exhibit"

Looks like react-exhibit is being distributed pre-compiled so that the process.env.PUBLIC_URL doesn't resolve based upon the upstream application but is fixed to 'react-exhibit'.

**Comment by au-re** [comment]
This issue is now fixed in the new versions of `react-exhibit` and `generate-react-exhibit`. You can fix this in an already existing project by updating `react-exhibit` to 2.0.3 and modifying these lines in `demo.js`:
```js
import "../node_modules/react-exhibit/dist/css/main.css";
```
to
```js
import "../node_modules/react-exhibit/lib/css/main.css";
```
and add a `baseURL` property to the Demo component like this:
```js
ReactDOM.render(<Demo
  readme={<Markdown>{readme}</Markdown>}
  baseURL={process.env.PUBLIC_URL}
  label="<%= appName %>"
  components={requireAllDemos()} />,
  document.getElementById("root"));
```
